// This file is auto-generated by organjsm tangle. Do not edit directly.
// Source: index.org

// [[file:index.org::667]]
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Threading;
using System.Threading.Channels;

namespace AgentRex {

public static partial class StreamOperators
{
  /// <summary>
  /// Creates a stream that emits a single value and then completes.
  /// </summary>
  public static async IAsyncEnumerable<T> Just<T>(
    T value,
    [EnumeratorCancellation] CancellationToken cancellationToken = default)
  {
    yield return value;
  }
  
  /// <summary>
  /// Alias for Just.
  /// </summary>
  public static IAsyncEnumerable<T> Of<T>(T value) => Just(value);
}
}
// unnamed ends here

// [[file:index.org::1085]]
namespace AgentRex {

public static partial class StreamOperators
{
/// <summary>
/// Creates a stream from a Task.
/// When the Task completes, the stream emits the value and finishes.
/// </summary>
public static async IAsyncEnumerable<T> FromTask<T>(
  Task<T> task,
  [EnumeratorCancellation] CancellationToken cancellationToken = default)
{
  var value = await task;
  yield return value;
}

/// <summary>
/// Creates a stream from an async function.
/// </summary>
public static async IAsyncEnumerable<T> FromAsync<T>(
  Func<Task<T>> asyncFunc,
  [EnumeratorCancellation] CancellationToken cancellationToken = default)
  {
  var value = await asyncFunc();
  yield return value;
}
}
}
// unnamed ends here

// [[file:index.org::1416]]
namespace AgentRex {

public static partial class StreamOperators
{
/// <summary>
/// Creates a stream from an enumerable.
/// Emits each value from the enumerable in sequence.
/// </summary>
public static async IAsyncEnumerable<T> From<T>(
  IEnumerable<T> source,
  [EnumeratorCancellation] CancellationToken cancellationToken = default)
{
  foreach (var item in source)
  {
    cancellationToken.ThrowIfCancellationRequested();
    yield return item;
  }
}

/// <summary>
/// Creates a stream from an async enumerable (passthrough).
/// </summary>
public static async IAsyncEnumerable<T> From<T>(
  IAsyncEnumerable<T> source,
  [EnumeratorCancellation] CancellationToken cancellationToken = default)
{
  await foreach (var item in source.WithCancellation(cancellationToken))
  {
    yield return item;
  }
}
}
}
// unnamed ends here

// [[file:index.org::1767]]
namespace AgentRex {
using System;


public static partial class StreamOperators
{
/// <summary>
/// Creates a stream that emits void at regular intervals.
/// To give it a value, combine it with Constant.
/// </summary>
public static async IAsyncEnumerable<Unit> Periodic(
  int intervalMs,
  [EnumeratorCancellation] CancellationToken cancellationToken = default)
{
  while (!cancellationToken.IsCancellationRequested)
  {
    yield return default;
    await Task.Delay(intervalMs, cancellationToken);
  }
}

/// <summary>
/// Unit type for void equivalent in generic contexts.
/// </summary>
public readonly struct Unit
{
  public static readonly Unit Default = default;
}
}
}
// unnamed ends here

// [[file:index.org::2017]]
namespace AgentRex {
using System.Linq;


public static partial class StreamOperators
{
/// <summary>
/// Creates a stream that immediately completes without emitting any values.
/// </summary>
public static async IAsyncEnumerable<T> Empty<T>()
{
  yield break;
}
}
}
// unnamed ends here

// [[file:index.org::2254]]
namespace AgentRex {

public static partial class StreamOperators
{
/// <summary>
/// Creates a stream that never emits any values and never completes.
/// </summary>
public static async IAsyncEnumerable<T> Never<T>(
  [EnumeratorCancellation] CancellationToken cancellationToken = default)
{
  // Wait indefinitely (or until cancellation)
  await Task.Delay(Timeout.Infinite, cancellationToken).ConfigureAwait(false);
  yield break; // Unreachable, but required for generator
}
}
}
// unnamed ends here

// [[file:index.org::2544]]
namespace AgentRex {

public static partial class StreamOperators
{
/// <summary>
/// Creates a stream that emits an infinite sequence by repeatedly applying a function.
/// </summary>
public static async IAsyncEnumerable<T> Iterate<T>(
  T seed,
  Func<T, T> fn,
  [EnumeratorCancellation] CancellationToken cancellationToken = default)
{
  var current = seed;
  while (!cancellationToken.IsCancellationRequested)
  {
    yield return current;
    current = fn(current);
  }
}
}
}
// unnamed ends here

// [[file:index.org::2953]]
namespace AgentRex {

/// <summary>
/// Result of an unfold step.
/// </summary>
public record UnfoldResult<T, S>(
  T Value,
  S NextSeed,
  bool Done
);

public static partial class StreamOperators
{
/// <summary>
/// Creates a stream by unfolding a seed value.
/// The function returns an object containing the next value, next seed, and done flag.
/// </summary>
public static async IAsyncEnumerable<T> Unfold<T, S>(
  S seed,
  Func<S, UnfoldResult<T, S>> fn,
  [EnumeratorCancellation] CancellationToken cancellationToken = default)
{
  var currentSeed = seed;
  while (!cancellationToken.IsCancellationRequested)
  {
    var result = fn(currentSeed);
    if (result.Done) break;
    yield return result.Value;
    currentSeed = result.NextSeed;
  }
}
}
}
// unnamed ends here

// [[file:index.org::3316]]
namespace AgentRex {

public static partial class StreamOperators
{
/// <summary>
/// Prepends a value to the beginning of a stream.
/// </summary>
public static async IAsyncEnumerable<T> StartWith<T>(
  T value,
  IAsyncEnumerable<T> stream,
  [EnumeratorCancellation] CancellationToken cancellationToken = default)
{
  yield return value;
  await foreach (var item in stream.WithCancellation(cancellationToken))
  {
    yield return item;
  }
}
}
}
// unnamed ends here

// [[file:index.org::3642]]
namespace AgentRex {

public static partial class StreamOperators
{
/// <summary>
/// Concatenates multiple streams into a single stream.
/// </summary>
public static async IAsyncEnumerable<T> Concat<T>(
  params IAsyncEnumerable<T>[] streams)
{
  foreach (var stream in streams)
  {
    await foreach (var item in stream)
    {
      yield return item;
    }
  }
}

/// <summary>
/// Concatenates two streams into a single stream.
/// </summary>
public static async IAsyncEnumerable<T> Concat<T>(
  IAsyncEnumerable<T> s1,
  IAsyncEnumerable<T> s2,
  [EnumeratorCancellation] CancellationToken cancellationToken = default)
{
  await foreach (var item in s1.WithCancellation(cancellationToken))
  {
    yield return item;
  }
  await foreach (var item in s2.WithCancellation(cancellationToken))
  {
    yield return item;
  }
}
}
}
// unnamed ends here

// [[file:index.org::4538]]
namespace AgentRex {

public static partial class StreamOperators
{
/// <summary>
/// Transforms each value emitted by a stream using a provided function.
/// </summary>
public static async IAsyncEnumerable<U> Map<T, U>(
  this IAsyncEnumerable<T> source,
  Func<T, U> fn,
  [EnumeratorCancellation] CancellationToken cancellationToken = default)
{
  await foreach (var item in source.WithCancellation(cancellationToken))
  {
    yield return fn(item);
  }
}

/// <summary>
/// Transforms each value using an async function.
/// </summary>
public static async IAsyncEnumerable<U> Map<T, U>(
  this IAsyncEnumerable<T> source,
  Func<T, Task<U>> fn,
  [EnumeratorCancellation] CancellationToken cancellationToken = default)
{
  await foreach (var item in source.WithCancellation(cancellationToken))
  {
    yield return await fn(item);
  }
}
}
}
// unnamed ends here

// [[file:index.org::4915]]
namespace AgentRex {

public static partial class StreamOperators
{
/// <summary>
/// Emits a constant value for each item in the source stream.
/// </summary>
public static async IAsyncEnumerable<TResult> Constant<TSource, TResult>(
  this IAsyncEnumerable<TSource> source,
  TResult value,
  [EnumeratorCancellation] CancellationToken cancellationToken = default)
{
  await foreach (var _ in source.WithCancellation(cancellationToken))
  {
    yield return value;
  }
}
}
}
// unnamed ends here

// [[file:index.org::5255]]
namespace AgentRex {

public static partial class StreamOperators
{
/// <summary>
/// Accumulates values using an accumulator function, emitting each intermediate result.
/// Yields the seed first, then each accumulated value.
/// </summary>
public static async IAsyncEnumerable<TAccumulate> Scan<TSource, TAccumulate>(
  this IAsyncEnumerable<TSource> source,
  TAccumulate seed,
  Func<TAccumulate, TSource, TAccumulate> accumulator,
  [EnumeratorCancellation] CancellationToken cancellationToken = default)
{
  var acc = seed;
  yield return acc;
  await foreach (var item in source.WithCancellation(cancellationToken))
  {
    acc = accumulator(acc, item);
    yield return acc;
  }
}

/// <summary>
/// Scan with async accumulator.
/// </summary>
public static async IAsyncEnumerable<TAccumulate> Scan<TSource, TAccumulate>(
  this IAsyncEnumerable<TSource> source,
  TAccumulate seed,
  Func<TAccumulate, TSource, Task<TAccumulate>> accumulator,
  [EnumeratorCancellation] CancellationToken cancellationToken = default)
{
  var acc = seed;
  yield return acc;
  await foreach (var item in source.WithCancellation(cancellationToken))
  {
    acc = await accumulator(acc, item);
    yield return acc;
  }
}
}
}
// unnamed ends here

// [[file:index.org::5673]]
namespace AgentRex {

public static partial class StreamOperators
{
/// <summary>
/// Performs side effects for each value without modifying them.
/// The side effect is fired without awaiting.
/// </summary>
public static async IAsyncEnumerable<T> Tap<T>(
  Action<T> sideEffect,
  IAsyncEnumerable<T> stream,
  [EnumeratorCancellation] CancellationToken cancellationToken = default)
{
  await foreach (var item in stream.WithCancellation(cancellationToken))
  {
    sideEffect(item);
    yield return item;
  }
}
}
}
// unnamed ends here

// [[file:index.org::5995]]
namespace AgentRex {

public static partial class StreamOperators
{
/// <summary>
/// Performs side effects for each value, awaiting completion before yielding.
/// </summary>
public static async IAsyncEnumerable<T> AwaitTap<T>(
  Func<T, Task> sideEffect,
  IAsyncEnumerable<T> stream,
  [EnumeratorCancellation] CancellationToken cancellationToken = default)
{
  await foreach (var item in stream.WithCancellation(cancellationToken))
  {
    await sideEffect(item);
    yield return item;
  }
}
}
}
// unnamed ends here

// [[file:index.org::6357]]
namespace AgentRex {

public static partial class StreamOperators
{
/// <summary>
/// Continues a stream with another stream once the first completes.
/// </summary>
public static async IAsyncEnumerable<T> ContinueWith<T>(
  Func<IAsyncEnumerable<T>> f,
  IAsyncEnumerable<T> stream,
  [EnumeratorCancellation] CancellationToken cancellationToken = default)
{
  await foreach (var item in stream.WithCancellation(cancellationToken))
  {
    yield return item;
  }
  await foreach (var item in f().WithCancellation(cancellationToken))
  {
    yield return item;
  }
}
}
}
// unnamed ends here

// [[file:index.org::6685]]
namespace AgentRex {

public static partial class StreamOperators
{
/// <summary>
/// Flattens a stream of streams by concatenating them into a single stream.
/// </summary>
public static async IAsyncEnumerable<T> ConcatAll<T>(
  IAsyncEnumerable<IAsyncEnumerable<T>> streamOfStreams,
  [EnumeratorCancellation] CancellationToken cancellationToken = default)
{
  await foreach (var innerStream in streamOfStreams.WithCancellation(cancellationToken))
  {
    await foreach (var item in innerStream.WithCancellation(cancellationToken))
    {
      yield return item;
    }
  }
}
}
}
// unnamed ends here

// [[file:index.org::7018]]
namespace AgentRex {

public static partial class StreamOperators
{
/// <summary>
/// Maps each value to a stream and concatenates the results in order.
/// </summary>
public static async IAsyncEnumerable<U> ConcatMap<T, U>(
  Func<T, IAsyncEnumerable<U>> f,
  IAsyncEnumerable<T> stream,
  [EnumeratorCancellation] CancellationToken cancellationToken = default)
{
  await foreach (var item in stream.WithCancellation(cancellationToken))
  {
    await foreach (var innerItem in f(item).WithCancellation(cancellationToken))
    {
      yield return innerItem;
    }
  }
}
}
}
// unnamed ends here

// [[file:index.org::7406]]
namespace AgentRex {

public static partial class StreamOperators
{
/// <summary>
/// Filters values emitted by a stream based on a provided predicate function.
/// </summary>
public static async IAsyncEnumerable<T> Filter<T>(
  this IAsyncEnumerable<T> source,
  Func<T, bool> predicate,
  [EnumeratorCancellation] CancellationToken cancellationToken = default)
{
  await foreach (var item in source.WithCancellation(cancellationToken))
  {
    if (predicate(item))
    {
      yield return item;
    }
  }
}

/// <summary>
/// Filters with an async predicate.
/// </summary>
public static async IAsyncEnumerable<T> Filter<T>(
    this IAsyncEnumerable<T> source,
    Func<T, Task<bool>> predicate,
    [EnumeratorCancellation] CancellationToken cancellationToken = default)
{
    await foreach (var item in source.WithCancellation(cancellationToken))
    {
        if (await predicate(item))
        {
            yield return item;
        }
    }
}
}
}
// unnamed ends here

// [[file:index.org::7980]]
namespace AgentRex {

public static partial class StreamOperators
{
/// <summary>
/// Filters out consecutive duplicate values from a stream.
/// </summary>
public static async IAsyncEnumerable<T> SkipRepeats<T>(
  IAsyncEnumerable<T> stream,
  [EnumeratorCancellation] CancellationToken cancellationToken = default)
{
  var first = true;
  T lastValue = default!;
  await foreach (var item in stream.WithCancellation(cancellationToken))
  {
    if (first || !EqualityComparer<T>.Default.Equals(item, lastValue))
    {
      yield return item;
      lastValue = item;
      first = false;
    }
  }
}

/// <summary>
/// Filters out consecutive duplicates using a custom equality function.
/// </summary>
public static async IAsyncEnumerable<T> SkipRepeatsWith<T>(
  Func<T, T, bool> equals,
  IAsyncEnumerable<T> stream,
  [EnumeratorCancellation] CancellationToken cancellationToken = default)
{
  var first = true;
  T lastValue = default!;
  await foreach (var item in stream.WithCancellation(cancellationToken))
  {
    if (first || !equals(item, lastValue))
    {
      yield return item;
      lastValue = item;
      first = false;
    }
  }
}
}
}
// unnamed ends here

// [[file:index.org::8419]]
namespace AgentRex {

public static partial class StreamOperators
{
/// <summary>
/// Takes only the first n values from a stream.
/// </summary>
public static async IAsyncEnumerable<T> Take<T>(
  this IAsyncEnumerable<T> source,
  int n,
  [EnumeratorCancellation] CancellationToken cancellationToken = default)
{
  var count = 0;
  await foreach (var item in source.WithCancellation(cancellationToken))
  {
    if (count++ < n)
    {
      yield return item;
    }
    else
    {
      break;
    }
  }
}
}
}
// unnamed ends here

// [[file:index.org::8758]]
namespace AgentRex {

public static partial class StreamOperators
{
/// <summary>
/// Skips the first n values from a stream.
/// </summary>
public static async IAsyncEnumerable<T> Skip<T>(
  this IAsyncEnumerable<T> source,
  int n,
  [EnumeratorCancellation] CancellationToken cancellationToken = default)
{
  var count = 0;
  await foreach (var item in source.WithCancellation(cancellationToken))
  {
    if (count++ >= n)
    {
      yield return item;
    }
  }
}
}
}
// unnamed ends here

// [[file:index.org::9136]]
namespace AgentRex {
public static partial class StreamOperators
{
/// <summary>
/// Emits values from index start to end (exclusive).
/// </summary>
public static async IAsyncEnumerable<T> Slice<T>(
  int start,
  int end,
  IAsyncEnumerable<T> stream,
  [EnumeratorCancellation] CancellationToken cancellationToken = default)
{
  var index = 0;
  await foreach (var item in stream.WithCancellation(cancellationToken))
  {
    if (index >= start && index < end)
    {
      yield return item;
    }
    index++;
    if (index >= end) break;
  }
}
}
}
// unnamed ends here

// [[file:index.org::9529]]
namespace AgentRex {
public static partial class StreamOperators
{
/// <summary>
/// Takes values from a stream while the predicate returns true.
/// </summary>
public static async IAsyncEnumerable<T> TakeWhile<T>(
  Func<T, bool> predicate,
  IAsyncEnumerable<T> stream,
  [EnumeratorCancellation] CancellationToken cancellationToken = default)
{
  await foreach (var item in stream.WithCancellation(cancellationToken))
  {
    if (predicate(item))
    {
      yield return item;
    }
    else
    {
      break;
    }
  }
}
}
}
// unnamed ends here

// [[file:index.org::9925]]
namespace AgentRex {
public static partial class StreamOperators
{
/// <summary>
/// Skips values while the predicate returns true, then emits the rest.
/// </summary>
public static async IAsyncEnumerable<T> SkipWhile<T>(
  Func<T, bool> predicate,
  IAsyncEnumerable<T> stream,
  [EnumeratorCancellation] CancellationToken cancellationToken = default)
{
  var skipping = true;
  await foreach (var item in stream.WithCancellation(cancellationToken))
  {
    if (skipping && !predicate(item))
    {
      skipping = false;
    }
    if (!skipping)
    {
      yield return item;
    }
  }
}
}
}
// unnamed ends here

// [[file:index.org::10320]]
namespace AgentRex {
public static partial class StreamOperators
{
/// <summary>
/// Takes values until the predicate matches (matching value not emitted).
/// </summary>
public static async IAsyncEnumerable<T> TakeUntil<T>(
  Func<T, bool> predicate,
  IAsyncEnumerable<T> stream,
  [EnumeratorCancellation] CancellationToken cancellationToken = default)
{
  await foreach (var item in stream.WithCancellation(cancellationToken))
  {
    if (predicate(item))
    {
      break;
    }
    yield return item;
  }
}
}
}
// unnamed ends here

// [[file:index.org::10760]]
namespace AgentRex {
public static partial class StreamOperators
{
/// <summary>
/// Delays each emission by the specified duration in milliseconds.
/// </summary>
public static async IAsyncEnumerable<T> Delay<T>(
  this IAsyncEnumerable<T> source,
  int delayMs,
  [EnumeratorCancellation] CancellationToken cancellationToken = default)
{
  await foreach (var item in source.WithCancellation(cancellationToken))
  {
    await Task.Delay(delayMs, cancellationToken);
    yield return item;
  }
}
}
}
// unnamed ends here

// [[file:index.org::11194]]
namespace AgentRex {
public static partial class StreamOperators
{
/// <summary>
/// Only emits a value if no new values arrive within the specified duration.
/// Waits for the stream to "settle" before emitting the most recent value.
/// </summary>
public static async IAsyncEnumerable<T> Debounce<T>(
  this IAsyncEnumerable<T> source,
  int durationMs,
  [EnumeratorCancellation] CancellationToken cancellationToken = default)
{
  T? pendingValue = default;
  bool hasPendingValue = false;
  CancellationTokenSource? debounceCts = null;
  var emitQueue = Channel.CreateUnbounded<T>();
  
  var consumeTask = Task.Run(async () =>
  {
    try
    {
      await foreach (var item in source.WithCancellation(cancellationToken))
      {
        debounceCts?.Cancel();
        pendingValue = item;
        hasPendingValue = true;
        debounceCts = new CancellationTokenSource();
        var localCts = debounceCts;
        
        _ = Task.Run(async () =>
        {
          try
          {
            await Task.Delay(durationMs, localCts.Token);
            if (hasPendingValue)
            {
              await emitQueue.Writer.WriteAsync(pendingValue!);
              hasPendingValue = false;
            }
          }
          catch (OperationCanceledException) { }
        });
      }
      
      // Give final debounce time to complete
      await Task.Delay(durationMs + 10);
      emitQueue.Writer.Complete();
    }
    catch (Exception ex)
    {
      emitQueue.Writer.Complete(ex);
    }
  });
  
  await foreach (var value in emitQueue.Reader.ReadAllAsync(cancellationToken))
  {
    yield return value;
  }
  
  await consumeTask;
}
}
}
// unnamed ends here

// [[file:index.org::11880]]
namespace AgentRex {

/// <summary>
/// Options for throttle behavior.
/// </summary>
public class ThrottleOptions
{
  public bool Leading { get; set; } = true;
  public bool Trailing { get; set; } = true;
  
  public static ThrottleOptions LeadingOnly() => new() { Leading = true, Trailing = false };
  public static ThrottleOptions TrailingOnly() => new() { Leading = false, Trailing = true };
}

public static partial class StreamOperators
{
/// <summary>
/// Limits the rate of emissions with leading/trailing edge control.
/// </summary>
public static async IAsyncEnumerable<T> Throttle<T>(
  this IAsyncEnumerable<T> source,
  int windowMs,
  ThrottleOptions? options = null,
  [EnumeratorCancellation] CancellationToken cancellationToken = default)
{
  options ??= new ThrottleOptions();
  var lastEmitTime = DateTimeOffset.MinValue;
  T? trailingValue = default;
  bool hasTrailing = false;
  
  await foreach (var item in source.WithCancellation(cancellationToken))
  {
    var now = DateTimeOffset.UtcNow;
    var elapsed = now - lastEmitTime;
    
    if (elapsed.TotalMilliseconds >= windowMs)
    {
      if (options.Leading)
      {
        yield return item;
        lastEmitTime = now;
        hasTrailing = false;
      }
      else
      {
        trailingValue = item;
        hasTrailing = true;
      }
    }
    else
    {
      trailingValue = item;
      hasTrailing = true;
    }
  }
  
  // Emit final trailing value if any
  if (hasTrailing && options.Trailing)
  {
    yield return trailingValue!;
  }
}
}
}
// unnamed ends here

// [[file:index.org::12464]]
namespace AgentRex {
public static partial class StreamOperators
{
/// <summary>
/// Recovers from errors by switching to an alternative stream.
/// </summary>
public static async IAsyncEnumerable<T> RecoverWith<T>(
  this IAsyncEnumerable<T> source,
  Func<Exception, IAsyncEnumerable<T>> recoverFn,
  [EnumeratorCancellation] CancellationToken cancellationToken = default)
{
  var queue = Channel.CreateUnbounded<(T? item, Exception? error, bool done)>();
  Exception? caughtException = null;
  
  // Producer task that handles errors
  _ = Task.Run(async () =>
  {
    try
    {
      await foreach (var item in source.WithCancellation(cancellationToken))
      {
        await queue.Writer.WriteAsync((item, null, false), cancellationToken);
      }
    }
    catch (Exception ex)
    {
      await queue.Writer.WriteAsync((default, ex, false), cancellationToken);
    }
    finally
    {
      await queue.Writer.WriteAsync((default, null, true), cancellationToken);
    }
  }, cancellationToken);
  
  // Consumer - yield items, capture errors
  await foreach (var (item, error, done) in queue.Reader.ReadAllAsync(cancellationToken))
  {
    if (done) break;
    if (error != null)
    {
      caughtException = error;
      break;
    }
    yield return item!;
  }
  
  if (caughtException != null)
  {
    await foreach (var item in recoverFn(caughtException).WithCancellation(cancellationToken))
    {
      yield return item;
    }
  }
}
}
}
// unnamed ends here

// [[file:index.org::13002]]
namespace AgentRex {
public static partial class StreamOperators
{
/// <summary>
/// Creates a stream that immediately throws an error when consumed.
/// </summary>
public static async IAsyncEnumerable<T> ThrowError<T>(Exception error)
{
  await Task.CompletedTask; // Make it async
  throw error;
  #pragma warning disable CS0162 // Unreachable code
  yield break;
  #pragma warning restore CS0162
}
}
}
// unnamed ends here

// [[file:index.org::13549]]
namespace AgentRex {

/// <summary>
/// Options for retry behavior.
/// </summary>
public class RetryOptions
{
  public int MaxAttempts { get; set; } = 3;
  public int DelayMs { get; set; } = 0;
  public Func<Exception, int, bool>? ShouldRetry { get; set; }
}

public static partial class StreamOperators
{
/// <summary>
/// Retries a stream factory when it errors. Uses a channel to avoid yield-in-try-catch.
/// </summary>
public static async IAsyncEnumerable<T> Retry<T>(
  Func<IAsyncEnumerable<T>> streamFactory,
  RetryOptions? options = null,
  [EnumeratorCancellation] CancellationToken cancellationToken = default)
{
  options ??= new RetryOptions();
  var attempt = 0;
  
  while (true)
  {
    var queue = Channel.CreateUnbounded<(T? item, Exception? error, bool done)>();
    Exception? caughtException = null;
    var completed = false;
    
    // Producer task that handles errors
    _ = Task.Run(async () =>
    {
      try
      {
        await foreach (var item in streamFactory().WithCancellation(cancellationToken))
        {
          await queue.Writer.WriteAsync((item, null, false), cancellationToken);
        }
        await queue.Writer.WriteAsync((default, null, true), cancellationToken); // Success
      }
      catch (Exception ex)
      {
        await queue.Writer.WriteAsync((default, ex, false), cancellationToken);
      }
    }, cancellationToken);
    
    // Consumer - yield items, capture errors
    await foreach (var (item, error, done) in queue.Reader.ReadAllAsync(cancellationToken))
    {
      if (done)
      {
        completed = true;
        break;
      }
      if (error != null)
      {
        caughtException = error;
        break;
      }
      yield return item!;
    }
    
    if (completed)
    {
      yield break; // Success - exit the retry loop
    }
    
    if (caughtException != null)
    {
      attempt++;
      var shouldRetry = options.ShouldRetry?.Invoke(caughtException, attempt) ?? true;
      
      if (attempt >= options.MaxAttempts || !shouldRetry)
      {
        throw caughtException;
      }
      
      if (options.DelayMs > 0)
      {
        await Task.Delay(options.DelayMs, cancellationToken);
      }
    }
  }
}
}
}
// unnamed ends here

// [[file:index.org::14220]]
namespace AgentRex {
public static partial class StreamOperators
{
/// <summary>
/// Merges multiple streams into a single stream, emitting values as they arrive.
/// </summary>
public static async IAsyncEnumerable<T> Merge<T>(
  params IAsyncEnumerable<T>[] sources)
{
  await foreach (var item in Merge((IEnumerable<IAsyncEnumerable<T>>)sources))
  {
    yield return item;
  }
}

/// <summary>
/// Merges multiple streams into a single stream, emitting values as they arrive.
/// </summary>
public static async IAsyncEnumerable<T> Merge<T>(
  IEnumerable<IAsyncEnumerable<T>> sources,
  [EnumeratorCancellation] CancellationToken cancellationToken = default)
{
  var queue = Channel.CreateUnbounded<T>();
  var sourceList = sources.ToList();
  var tasks = new List<Task>();
  
  foreach (var source in sourceList)
  {
    tasks.Add(Task.Run(async () =>
    {
      await foreach (var item in source.WithCancellation(cancellationToken))
      {
        await queue.Writer.WriteAsync(item, cancellationToken);
      }
    }, cancellationToken));
  }
  
  _ = Task.Run(async () =>
  {
    await Task.WhenAll(tasks);
    queue.Writer.Complete();
  }, cancellationToken);
  
  await foreach (var item in queue.Reader.ReadAllAsync(cancellationToken))
  {
    yield return item;
  }
}
}
}
// unnamed ends here

// [[file:index.org::14608]]
namespace AgentRex {
public static partial class StreamOperators
{
/// <summary>
/// Flattens a stream of streams by merging them into a single stream.
/// </summary>
public static async IAsyncEnumerable<T> MergeAll<T>(
  this IAsyncEnumerable<IAsyncEnumerable<T>> streamOfStreams,
  [EnumeratorCancellation] CancellationToken cancellationToken = default)
{
  var queue = Channel.CreateUnbounded<T>();
  var tasks = new List<Task>();
  var outerComplete = false;
  
  var outerTask = Task.Run(async () =>
  {
    await foreach (var innerStream in streamOfStreams.WithCancellation(cancellationToken))
    {
      tasks.Add(Task.Run(async () =>
      {
        await foreach (var item in innerStream.WithCancellation(cancellationToken))
        {
          await queue.Writer.WriteAsync(item, cancellationToken);
        }
      }, cancellationToken));
    }
    outerComplete = true;
    await Task.WhenAll(tasks);
    queue.Writer.Complete();
  }, cancellationToken);
  
  await foreach (var item in queue.Reader.ReadAllAsync(cancellationToken))
  {
    yield return item;
  }
  
  await outerTask;
}
}
}
// unnamed ends here

// [[file:index.org::15032]]
namespace AgentRex {
using System.Collections.Concurrent;

public static partial class StreamOperators
{
/// <summary>
/// Maps each value to a stream and flattens the results concurrently.
/// Also known as chain in some libraries.
/// </summary>
public static async IAsyncEnumerable<TResult> Chain<TSource, TResult>(
  this IAsyncEnumerable<TSource> source,
  Func<TSource, IAsyncEnumerable<TResult>> selector,
  [EnumeratorCancellation] CancellationToken cancellationToken = default)
{
  var queue = new ConcurrentQueue<TResult>();
  var tasks = new List<Task>();
  var completed = false;
  
  var producerTask = Task.Run(async () =>
  {
    await foreach (var item in source.WithCancellation(cancellationToken))
    {
      var innerStream = selector(item);
      var task = Task.Run(async () =>
      {
        await foreach (var innerItem in innerStream.WithCancellation(cancellationToken))
        {
          queue.Enqueue(innerItem);
        }
      }, cancellationToken);
      tasks.Add(task);
    }
    await Task.WhenAll(tasks);
    completed = true;
  }, cancellationToken);
  
  while (!completed || !queue.IsEmpty)
  {
    if (queue.TryDequeue(out var item))
    {
      yield return item;
    }
    else
    {
      await Task.Delay(1, cancellationToken);
    }
  }
  
  await producerTask;
}

/// <summary>
/// Alias for Chain.
/// </summary>
public static IAsyncEnumerable<TResult> FlatMap<TSource, TResult>(
  this IAsyncEnumerable<TSource> source,
  Func<TSource, IAsyncEnumerable<TResult>> selector) => 
  source.Chain(selector);
}
}
// unnamed ends here

// [[file:index.org::15521]]
namespace AgentRex {
public static partial class StreamOperators
{
/// <summary>
/// Maps each value to a stream, canceling the previous inner stream when a new value arrives.
/// Only values from the most recent inner stream are emitted.
/// </summary>
public static async IAsyncEnumerable<TResult> SwitchMap<TSource, TResult>(
  this IAsyncEnumerable<TSource> source,
  Func<TSource, IAsyncEnumerable<TResult>> selector,
  [EnumeratorCancellation] CancellationToken cancellationToken = default)
{
  var queue = Channel.CreateUnbounded<(TResult? value, bool isDone)>();
  CancellationTokenSource? currentInnerCts = null;
  var outerDone = false;
  
  var outerTask = Task.Run(async () =>
  {
    try
    {
      await foreach (var item in source.WithCancellation(cancellationToken))
      {
        // Cancel previous inner stream
        currentInnerCts?.Cancel();
        currentInnerCts = new CancellationTokenSource();
        var localCts = currentInnerCts;
        
        _ = Task.Run(async () =>
        {
          try
          {
            await foreach (var innerItem in selector(item).WithCancellation(localCts.Token))
            {
              await queue.Writer.WriteAsync((innerItem, false), cancellationToken);
            }
          }
          catch (OperationCanceledException) { }
        }, cancellationToken);
      }
      
      outerDone = true;
      // Wait a bit for final inner stream
      await Task.Delay(100, cancellationToken);
      queue.Writer.Complete();
    }
    catch (Exception ex)
    {
      queue.Writer.Complete(ex);
    }
  }, cancellationToken);
  
  await foreach (var (value, isDone) in queue.Reader.ReadAllAsync(cancellationToken))
  {
    if (!isDone && value != null)
    {
      yield return value;
    }
  }
  
  await outerTask;
}
}
}
// unnamed ends here

// [[file:index.org::15967]]
namespace AgentRex {
public static partial class StreamOperators
{
/// <summary>
/// Combines two streams, emitting tuples of latest values whenever either emits.
/// Only starts emitting after both streams have produced at least one value.
/// </summary>
public static async IAsyncEnumerable<(T1, T2)> Latest<T1, T2>(
  IAsyncEnumerable<T1> stream1,
  IAsyncEnumerable<T2> stream2,
  [EnumeratorCancellation] CancellationToken cancellationToken = default)
{
  T1? latest1 = default;
  T2? latest2 = default;
  bool has1 = false;
  bool has2 = false;
  var queue = Channel.CreateUnbounded<(int, object?)>();
  
  var task1 = Task.Run(async () =>
  {
    await foreach (var item in stream1.WithCancellation(cancellationToken))
    {
      await queue.Writer.WriteAsync((1, item), cancellationToken);
    }
  }, cancellationToken);
  
  var task2 = Task.Run(async () =>
  {
    await foreach (var item in stream2.WithCancellation(cancellationToken))
    {
      await queue.Writer.WriteAsync((2, item), cancellationToken);
    }
  }, cancellationToken);
  
  _ = Task.Run(async () =>
  {
    await Task.WhenAll(task1, task2);
    queue.Writer.Complete();
  }, cancellationToken);
  
  await foreach (var (streamId, value) in queue.Reader.ReadAllAsync(cancellationToken))
  {
    if (streamId == 1)
    {
      latest1 = (T1)value!;
      has1 = true;
    }
    else
    {
      latest2 = (T2)value!;
      has2 = true;
    }
    
    if (has1 && has2)
    {
      yield return (latest1!, latest2!);
    }
  }
}
}
}
// unnamed ends here

// [[file:index.org::16288]]
namespace AgentRex {
public static partial class StreamOperators
{
/// <summary>
/// Applies the latest function to the latest value.
/// </summary>
public static IAsyncEnumerable<TResult> ApplyLatest<T, TResult>(
  IAsyncEnumerable<Func<T, TResult>> fnStream,
  IAsyncEnumerable<T> valueStream) =>
  Latest(fnStream, valueStream)
    .Select(tuple => tuple.Item1(tuple.Item2));
}
}
// unnamed ends here

// [[file:index.org::16647]]
namespace AgentRex {
public static partial class StreamOperators
{
/// <summary>
/// Emits values from source until stop stream emits.
/// </summary>
public static async IAsyncEnumerable<T> UntilStream<T, TStop>(
  this IAsyncEnumerable<T> source,
  IAsyncEnumerable<TStop> stop,
  [EnumeratorCancellation] CancellationToken cancellationToken = default)
{
  using var stopCts = new CancellationTokenSource();
  using var linkedCts = CancellationTokenSource.CreateLinkedTokenSource(cancellationToken, stopCts.Token);
  
  _ = Task.Run(async () =>
  {
    await foreach (var _ in stop.WithCancellation(cancellationToken))
    {
      stopCts.Cancel();
      break;
    }
  }, cancellationToken);
  
  await foreach (var item in source.WithCancellation(linkedCts.Token).ConfigureAwait(false))
  {
    yield return item;
  }
}
}
}
// unnamed ends here

// [[file:index.org::17016]]
namespace AgentRex {
public static partial class StreamOperators
{
/// <summary>
/// Emits values from source only after start stream emits.
/// </summary>
public static async IAsyncEnumerable<T> SinceStream<T, TStart>(
  this IAsyncEnumerable<T> source,
  IAsyncEnumerable<TStart> start,
  [EnumeratorCancellation] CancellationToken cancellationToken = default)
{
  // Wait for the start signal first
  await foreach (var _ in start.WithCancellation(cancellationToken))
  {
    break; // First value triggers start
  }
  
  // Now emit all values from source
  await foreach (var item in source.WithCancellation(cancellationToken))
  {
    yield return item;
  }
}
}
}
// unnamed ends here

// [[file:index.org::17363]]
namespace AgentRex {
public static partial class StreamOperators
{
/// <summary>
/// Collects values into lists of the specified size.
/// </summary>
public static async IAsyncEnumerable<List<T>> Buffer<T>(
  this IAsyncEnumerable<T> source,
  int size,
  [EnumeratorCancellation] CancellationToken cancellationToken = default)
{
  var buffer = new List<T>(size);
  
  await foreach (var item in source.WithCancellation(cancellationToken))
  {
    buffer.Add(item);
    if (buffer.Count >= size)
    {
      yield return buffer;
      buffer = new List<T>(size);
    }
  }
  
  if (buffer.Count > 0)
  {
    yield return buffer;
  }
}
}
}
// unnamed ends here

// [[file:index.org::17745]]
namespace AgentRex {
public static partial class StreamOperators
{
/// <summary>
/// Collects values over time windows.
/// </summary>
public static async IAsyncEnumerable<List<T>> BufferTime<T>(
  this IAsyncEnumerable<T> source,
  int milliseconds,
  [EnumeratorCancellation] CancellationToken cancellationToken = default)
{
  var buffer = new List<T>();
  using var cts = CancellationTokenSource.CreateLinkedTokenSource(cancellationToken);
  var lastEmit = DateTimeOffset.UtcNow;
  
  await foreach (var item in source.WithCancellation(cancellationToken))
  {
    buffer.Add(item);
    var now = DateTimeOffset.UtcNow;
    
    if ((now - lastEmit).TotalMilliseconds >= milliseconds)
    {
      if (buffer.Count > 0)
      {
        yield return buffer;
        buffer = new List<T>();
      }
      lastEmit = now;
    }
  }
  
  if (buffer.Count > 0)
  {
    yield return buffer;
  }
}
}
}
// unnamed ends here

// [[file:index.org::18191]]
namespace AgentRex {
public static partial class StreamOperators
{
/// <summary>
/// Splits source into windows of specified size.
/// Simplified to return lists like Buffer.
/// </summary>
public static IAsyncEnumerable<List<T>> Window<T>(
  this IAsyncEnumerable<T> source,
  int size) => source.Buffer(size);
}
}
// unnamed ends here

// [[file:index.org::18694]]
namespace AgentRex {
public static partial class StreamOperators
{
/// <summary>
/// Pre-fetches values from source into a buffer.
/// </summary>
public static async IAsyncEnumerable<T> Eager<T>(
  this IAsyncEnumerable<T> source,
  int bufferSize,
  [EnumeratorCancellation] CancellationToken cancellationToken = default)
{
  var channel = Channel.CreateBounded<T>(new BoundedChannelOptions(bufferSize > 0 ? bufferSize : 1000)
  {
    FullMode = BoundedChannelFullMode.Wait
  });
  
  var producerTask = Task.Run(async () =>
  {
    try
    {
      await foreach (var item in source.WithCancellation(cancellationToken))
      {
        await channel.Writer.WriteAsync(item, cancellationToken);
      }
      channel.Writer.Complete();
    }
    catch (Exception ex)
    {
      channel.Writer.Complete(ex);
    }
  }, cancellationToken);
  
  await foreach (var item in channel.Reader.ReadAllAsync(cancellationToken))
  {
    yield return item;
  }
}

/// <summary>
/// Pre-fetches values immediately on creation.
/// </summary>
public static IAsyncEnumerable<T> EagerNow<T>(
  this IAsyncEnumerable<T> source,
  int bufferSize) => source.Eager(bufferSize);
}
}
// unnamed ends here

// [[file:index.org::19768]]
namespace AgentRex {
using System.Threading.Channels;

/// <summary>
/// A multicasting subject that replays buffered values to new subscribers.
/// Simplified implementation using Channels.
/// </summary>
public class ReplaySubject<T>
{
  private readonly int _bufferSize;
  private readonly List<T> _buffer = new();
  private readonly List<Channel<T>> _subscribers = new();
  private bool _completed = false;
  
  public ReplaySubject(int bufferSize = int.MaxValue)
  {
    _bufferSize = bufferSize;
  }
  
  public void Next(T value)
  {
    if (_completed) throw new InvalidOperationException("Cannot push to completed ReplaySubject");
    
    _buffer.Add(value);
    if (_buffer.Count > _bufferSize)
    {
      _buffer.RemoveAt(0);
    }
    
    foreach (var sub in _subscribers)
    {
      sub.Writer.TryWrite(value);
    }
  }
  
  public void Complete()
  {
    _completed = true;
    foreach (var sub in _subscribers)
    {
      sub.Writer.Complete();
    }
  }
  
  public async IAsyncEnumerable<T> Subscribe([EnumeratorCancellation] CancellationToken cancellationToken = default)
  {
    var channel = Channel.CreateUnbounded<T>();
    _subscribers.Add(channel);
    
    // Replay buffered values first
    foreach (var value in _buffer)
    {
      yield return value;
    }
    
    if (_completed)
    {
      yield break;
    }
    
    // Then receive live values
    await foreach (var value in channel.Reader.ReadAllAsync(cancellationToken))
    {
      yield return value;
    }
  }
  
  public IReadOnlyList<T> GetBuffer() => _buffer.AsReadOnly();
  
  public int SubscriberCount => _subscribers.Count;
}
}
// unnamed ends here

// [[file:index.org::20149]]
namespace AgentRex {
public static partial class StreamOperators
{
/// <summary>
/// Creates a replay wrapper for a stream.
/// </summary>
public static ReplaySubject<T> Replay<T>(
  this IAsyncEnumerable<T> source,
  int bufferSize)
{
  var subject = new ReplaySubject<T>(bufferSize);
  
  // Start consuming source and feeding subject
  _ = Task.Run(async () =>
  {
    try
    {
      await foreach (var item in source)
      {
        subject.Next(item);
      }
      subject.Complete();
    }
    catch (Exception)
    {
      subject.Complete();
    }
  });
  
  return subject;
}

/// <summary>
/// Shares a stream without buffering.
/// </summary>
public static ReplaySubject<T> Share<T>(
  this IAsyncEnumerable<T> source) =>
  source.Replay(0);
}
}
// unnamed ends here

// [[file:index.org::20532]]
namespace AgentRex {
public static partial class StreamOperators
{
/// <summary>
/// Creates a factory that produces independent copies of a buffered stream.
/// </summary>
public static Func<IAsyncEnumerable<T>> ReplayFactory<T>(
  this IAsyncEnumerable<T> source,
  int bufferSize)
{
  var subject = source.Replay(bufferSize);
  return () => subject.Subscribe();
}
}
}
// unnamed ends here
