// This file is auto-generated by organjsm tangle. Do not edit directly.
// Source: index.org

// [[file:index.org::16306]]
using System;
using System.Linq;
using System.Threading.Tasks;
using Xunit;

namespace AgentRex.Tests;

public class ApplyLatestTests
{
  [Fact]
  public async Task ApplyLatest_AppliesFunctionToValue()
  {
    var fns = StreamOperators.From(new Func<int, int>[] { x => x * 2, x => x * 3 });
    var vals = StreamOperators.From(new[] { 10, 20 });
    var values = await StreamOperators.ApplyLatest(fns, vals).ToListAsync();
    Assert.NotEmpty(values);
  }
}
// unnamed ends here
