// This file is auto-generated by organjsm tangle. Do not edit directly.
// Source: index.org

// [[file:index.org::17830]]
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Xunit;

namespace AgentRex.Tests;

public class BufferTimeTests
{
  [Fact]
  public async Task BufferTime_CollectsOverTimeWindows()
  {
    var source = StreamOperators.From(new[] { 1, 2, 3, 4 });
    var values = await source.BufferTime(100).ToListAsync();
    Assert.True(values.SelectMany(x => x).SequenceEqual(new[] { 1, 2, 3, 4 }));
  }
}
// unnamed ends here
