// This file is auto-generated by organjsm tangle. Do not edit directly.
// Source: index.org

// [[file:index.org::17440]]
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Xunit;

namespace AgentRex.Tests;

public class BufferTests
{
  [Fact]
  public async Task Buffer_CollectsIntoFixedSizeLists()
  {
    var source = StreamOperators.From(new[] { 1, 2, 3, 4, 5 });
    var values = await source.Buffer(2).ToListAsync();
    Assert.Equal(3, values.Count);
    Assert.Equal(new List<int> { 1, 2 }, values[0]);
    Assert.Equal(new List<int> { 3, 4 }, values[1]);
    Assert.Equal(new List<int> { 5 }, values[2]);
  }
}
// unnamed ends here
