// This file is auto-generated by organjsm tangle. Do not edit directly.
// Source: index.org

// [[file:index.org::15096]]
using System;
using System.Linq;
using System.Threading.Tasks;
using Xunit;

namespace AgentRex.Tests;

public class ChainTests
{
  [Fact]
  public async Task Chain_FlattensInnerStreams()
  {
    var values = await StreamOperators.From(new[] { 1, 2 })
      .Chain(x => StreamOperators.From(new[] { x * 10, x * 10 + 1 }))
      .ToListAsync();
    // Concurrent, check for all values
    var valueSet = values.ToHashSet();
    Assert.Contains(10, valueSet);
    Assert.Contains(11, valueSet);
    Assert.Contains(20, valueSet);
    Assert.Contains(21, valueSet);
  }
  
  [Fact]
  public async Task FlatMap_IsAliasForChain()
  {
    var values = await StreamOperators.From(new[] { 1, 2 })
      .FlatMap(x => StreamOperators.From(new[] { x, x * 2 }))
      .ToListAsync();
    Assert.Equal(4, values.Count);
  }
}
// unnamed ends here
