// This file is auto-generated by organjsm tangle. Do not edit directly.
// Source: index.org

// [[file:index.org::7045]]
using System;
using System.Linq;
using System.Threading.Tasks;
using Xunit;

namespace AgentRex.Tests;

public class ConcatMapTests
{
  [Fact]
  public async Task ConcatMap_MapsAndConcatenates()
  {
    var values = await StreamOperators.ConcatMap(
      x => StreamOperators.From(new[] { x * 10, x * 10 + 1 }),
      StreamOperators.From(new[] { 1, 2 })
    ).ToListAsync();
    Assert.Equal(new[] { 10, 11, 20, 21 }, values);
  }
  
  [Fact]
  public async Task ConcatMap_HandlesEmptyResults()
  {
    var values = await StreamOperators.ConcatMap(
      x => x > 1 ? StreamOperators.From(new[] { x }) : StreamOperators.Empty<int>(),
      StreamOperators.From(new[] { 1, 2, 3 })
    ).ToListAsync();
    Assert.Equal(new[] { 2, 3 }, values);
  }
}
// unnamed ends here
