// This file is auto-generated by organjsm tangle. Do not edit directly.
// Source: index.org

// [[file:index.org::3685]]
using System.Linq;
using System.Threading.Tasks;
using Xunit;

namespace AgentRex.Tests;

public class ConcatTests
{
  [Fact]
  public async Task Concat_JoinsStreams()
  {
    var values = await StreamOperators.Concat(
      StreamOperators.From(new[] { 1, 2 }),
      StreamOperators.From(new[] { 3, 4 })
    ).ToListAsync();
    Assert.Equal(new[] { 1, 2, 3, 4 }, values);
  }
  
  [Fact]
  public async Task Concat_WithEmptyFirst()
  {
    var values = await StreamOperators.Concat(
      StreamOperators.Empty<int>(),
      StreamOperators.From(new[] { 5, 6 })
    ).ToListAsync();
    Assert.Equal(new[] { 5, 6 }, values);
  }
  
  [Fact]
  public async Task Concat_MultipleStreams()
  {
    var values = await StreamOperators.Concat(
      StreamOperators.From(new[] { 1 }),
      StreamOperators.From(new[] { 2, 3 }),
      StreamOperators.From(new[] { 4 })
    ).ToListAsync();
    Assert.Equal(new[] { 1, 2, 3, 4 }, values);
  }
}
// unnamed ends here
