// This file is auto-generated by organjsm tangle. Do not edit directly.
// Source: index.org

// [[file:index.org::6711]]
using System.Linq;
using System.Threading.Tasks;
using Xunit;

namespace AgentRex.Tests;

public class ConcatAllTests
{
  [Fact]
  public async Task ConcatAll_FlattensStreamOfStreams()
  {
    async System.Collections.Generic.IAsyncEnumerable<System.Collections.Generic.IAsyncEnumerable<int>> MakeStreamOfStreams()
    {
      yield return StreamOperators.From(new[] { 1, 2 });
      yield return StreamOperators.From(new[] { 3, 4 });
    }
    
    var values = await StreamOperators.ConcatAll(MakeStreamOfStreams()).ToListAsync();
    Assert.Equal(new[] { 1, 2, 3, 4 }, values);
  }
}
// unnamed ends here
