// This file is auto-generated by organjsm tangle. Do not edit directly.
// Source: index.org

// [[file:index.org::4939]]
using System;
using System.Linq;
using System.Threading.Tasks;
using Xunit;

namespace AgentRex.Tests;

public class ConstantTests
{
  [Fact]
  public async Task Constant_ReplacesAllValues()
  {
    var values = await StreamOperators.From(new[] { 1, 2, 3 })
      .Constant("x")
      .ToListAsync();
    Assert.Equal(new[] { "x", "x", "x" }, values);
  }
  
  [Fact]
  public async Task Constant_EmptyStream()
  {
    var values = await StreamOperators.From(Array.Empty<int>())
      .Constant(42)
      .ToListAsync();
    Assert.Empty(values);
  }
}
// unnamed ends here
