// This file is auto-generated by organjsm tangle. Do not edit directly.
// Source: index.org

// [[file:index.org::6385]]
using System;
using System.Linq;
using System.Threading.Tasks;
using Xunit;

namespace AgentRex.Tests;

public class ContinueWithTests
{
  [Fact]
  public async Task ContinueWith_AppendsStream()
  {
    var values = await StreamOperators.ContinueWith(
      () => StreamOperators.From(new[] { 3, 4 }),
      StreamOperators.From(new[] { 1, 2 })
    ).ToListAsync();
    Assert.Equal(new[] { 1, 2, 3, 4 }, values);
  }
  
  [Fact]
  public async Task ContinueWith_IsLazy()
  {
    var called = false;
    var values = await StreamOperators.ContinueWith(
      () => {
        called = true;
        return StreamOperators.From(new[] { 99 });
      },
      StreamOperators.From(new[] { 1 })
    ).ToListAsync();
    Assert.True(called);
    Assert.Equal(new[] { 1, 99 }, values);
  }
}
// unnamed ends here
