// This file is auto-generated by organjsm tangle. Do not edit directly.
// Source: index.org

// [[file:index.org::11262]]
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Xunit;

namespace AgentRex.Tests;

public class DebounceTests
{
  [Fact]
  public async Task Debounce_EmitsOnlySettledValues()
  {
    async IAsyncEnumerable<int> Source()
    {
      yield return 1;
      await Task.Delay(10);
      yield return 2;
      await Task.Delay(10);
      yield return 3;
      await Task.Delay(50); // Let it settle
    }
    
    var values = await Source()
      .Debounce(30)
      .ToListAsync();
    // Only the last value should be emitted
    Assert.Equal(new[] { 3 }, values);
  }
  
  [Fact]
  public async Task Debounce_WithLargeGapsEmitsMultipleValues()
  {
    async IAsyncEnumerable<int> Source()
    {
      yield return 1;
      await Task.Delay(50);
      yield return 2;
    }
    
    var values = await Source()
      .Debounce(20)
      .ToListAsync();
    // Both should emit since delay > debounce time
    Assert.Equal(new[] { 1, 2 }, values);
  }
}
// unnamed ends here
