// This file is auto-generated by organjsm tangle. Do not edit directly.
// Source: index.org

// [[file:index.org::10784]]
using System;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Xunit;

namespace AgentRex.Tests;

public class DelayTests
{
  [Fact]
  public async Task Delay_DelaysEachEmission()
  {
    var sw = Stopwatch.StartNew();
    var values = await StreamOperators.From(new[] { 1, 2, 3 })
      .Delay(20)
      .ToListAsync();
    sw.Stop();
    Assert.Equal(new[] { 1, 2, 3 }, values);
    Assert.True(sw.ElapsedMilliseconds >= 50); // ~60ms for 3 items
  }
  
  [Fact]
  public async Task Delay_EmptyStream()
  {
    var values = await StreamOperators.From(Array.Empty<int>())
      .Delay(100)
      .ToListAsync();
    Assert.Empty(values);
  }
}
// unnamed ends here
