// This file is auto-generated by organjsm tangle. Do not edit directly.
// Source: index.org

// [[file:index.org::18787]]
using System;
using System.Linq;
using System.Threading.Tasks;
using Xunit;

namespace AgentRex.Tests;

public class EagerTests
{
  [Fact]
  public async Task Eager_PrefetchesValues()
  {
    var source = StreamOperators.From(new[] { 1, 2, 3 });
    var values = await source.Eager(2).ToListAsync();
    Assert.Equal(new[] { 1, 2, 3 }, values);
  }
}
// unnamed ends here
