// This file is auto-generated by organjsm tangle. Do not edit directly.
// Source: index.org

// [[file:index.org::2037]]
using System.Linq;
using System.Threading.Tasks;
using Xunit;

namespace AgentRex.Tests;

public class EmptyTests
{
  [Fact]
  public async Task Empty_CompletesImmediately()
  {
    var values = await StreamOperators.Empty<int>().ToListAsync();
    Assert.Empty(values);
  }
}
// unnamed ends here
