// This file is auto-generated by organjsm tangle. Do not edit directly.
// Source: index.org

// [[file:index.org::7450]]
using System;
using System.Linq;
using System.Threading.Tasks;
using Xunit;

namespace AgentRex.Tests;

public class FilterTests
{
    [Fact]
    public async Task Filter_KeepsMatchingValues()
    {
        var values = await StreamOperators.From(new[] { 1, 2, 3, 4, 5 })
            .Filter(x => x > 2)
            .ToListAsync();
        Assert.Equal(new[] { 3, 4, 5 }, values);
    }
    
    [Fact]
    public async Task Filter_EvenNumbers()
    {
        var values = await StreamOperators.From(new[] { 1, 2, 3, 4, 5, 6 })
            .Filter(x => x % 2 == 0)
            .ToListAsync();
        Assert.Equal(new[] { 2, 4, 6 }, values);
    }
    
    [Fact]
    public async Task Filter_WithAsyncPredicate()
    {
        var values = await StreamOperators.From(new[] { 1, 2, 3, 4 })
            .Filter(async x =>
            {
                await Task.Delay(1);
                return x % 2 == 0;
            })
            .ToListAsync();
        Assert.Equal(new[] { 2, 4 }, values);
    }
}
// unnamed ends here
