// This file is auto-generated by organjsm tangle. Do not edit directly.
// Source: index.org

// [[file:index.org::1118]]
using System.Linq;
using System.Threading.Tasks;
using Xunit;

namespace AgentRex.Tests;

public class FromTaskTests
{
  [Fact]
  public async Task FromTask_EmitsResolvedValue()
  {
    var values = await StreamOperators.FromTask(Task.FromResult(42)).ToListAsync();
    Assert.Equal(new[] { 42 }, values);
  }
  
  [Fact]
  public async Task FromAsync_EmitsComputedValue()
  {
    var values = await StreamOperators.FromAsync(async () =>
    {
      await Task.Delay(1);
      return "computed";
    }).ToListAsync();
    Assert.Equal(new[] { "computed" }, values);
  }
}
// unnamed ends here
