// This file is auto-generated by organjsm tangle. Do not edit directly.
// Source: index.org

// [[file:index.org::1454]]
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Xunit;

namespace AgentRex.Tests;

public class FromTests
{
  [Fact]
  public async Task From_EmitsAllValuesFromArray()
  {
    var values = await StreamOperators.From(new[] { 1, 2, 3 }).ToListAsync();
    Assert.Equal(new[] { 1, 2, 3 }, values);
  }
  
  [Fact]
  public async Task From_HandlesEmptyArray()
  {
    var values = await StreamOperators.From(Array.Empty<int>()).ToListAsync();
    Assert.Empty(values);
  }
  
  [Fact]
  public async Task From_WorksWithList()
  {
    var values = await StreamOperators.From(new List<int> { 4, 5, 6 }).ToListAsync();
    Assert.Equal(new[] { 4, 5, 6 }, values);
  }
}
// unnamed ends here
