// This file is auto-generated by organjsm tangle. Do not edit directly.
// Source: index.org

// [[file:index.org::2570]]
using System;
using System.Linq;
using System.Threading.Tasks;
using Xunit;

namespace AgentRex.Tests;

public class IterateTests
{
  [Fact]
  public async Task Iterate_GeneratesSequence()
  {
    var values = await StreamOperators.Iterate(1, x => x * 2).Take(5).ToListAsync();
    Assert.Equal(new[] { 1, 2, 4, 8, 16 }, values);
  }
  
  [Fact]
  public async Task Iterate_WithAddition()
  {
    var values = await StreamOperators.Iterate(0, x => x + 1).Take(4).ToListAsync();
    Assert.Equal(new[] { 0, 1, 2, 3 }, values);
  }
}
// unnamed ends here
