// This file is auto-generated by organjsm tangle. Do not edit directly.
// Source: index.org

// [[file:index.org::697]]
using System.Linq;
using System.Threading.Tasks;
using Xunit;

namespace AgentRex.Tests;

public class JustTests
{
  [Fact]
  public async Task Just_EmitsSingleValue()
  {
    var values = await StreamOperators.Just(42).ToListAsync();
    Assert.Equal(new[] { 42 }, values);
  }
  
  [Fact]
  public async Task Of_IsAliasForJust()
  {
    var values = await StreamOperators.Of("hello").ToListAsync();
    Assert.Equal(new[] { "hello" }, values);
  }
}
// unnamed ends here
