// This file is auto-generated by organjsm tangle. Do not edit directly.
// Source: index.org

// [[file:index.org::16033]]
using System;
using System.Linq;
using System.Threading.Tasks;
using Xunit;

namespace AgentRex.Tests;

public class LatestTests
{
  [Fact]
  public async Task Latest_CombinesTwoStreams()
  {
    var s1 = StreamOperators.From(new[] { 1, 2 });
    var s2 = StreamOperators.From(new[] { "a", "b" });
    var values = await StreamOperators.Latest(s1, s2).ToListAsync();
    // Should emit tuples after both have values
    Assert.NotEmpty(values);
  }
}
// unnamed ends here
