// This file is auto-generated by organjsm tangle. Do not edit directly.
// Source: index.org

// [[file:index.org::4576]]
using System;
using System.Linq;
using System.Threading.Tasks;
using Xunit;

namespace AgentRex.Tests;

public class MapTests
{
  [Fact]
  public async Task Map_TransformsValues()
  {
    var values = await StreamOperators.From(new[] { 1, 2, 3 })
      .Map(x => x * 2)
      .ToListAsync();
    Assert.Equal(new[] { 2, 4, 6 }, values);
  }
  
  [Fact]
  public async Task Map_WithAsyncTransform()
  {
    var values = await StreamOperators.From(new[] { 1, 2, 3 })
      .Map(async x =>
      {
        await Task.Delay(1);
        return x * 10;
      })
      .ToListAsync();
    Assert.Equal(new[] { 10, 20, 30 }, values);
  }
}
// unnamed ends here
