// This file is auto-generated by organjsm tangle. Do not edit directly.
// Source: index.org

// [[file:index.org::14274]]
using System;
using System.Linq;
using System.Threading.Tasks;
using Xunit;

namespace AgentRex.Tests;

public class MergeTests
{
  [Fact]
  public async Task Merge_CombinesMultipleStreams()
  {
    var s1 = StreamOperators.From(new[] { 1, 3, 5 });
    var s2 = StreamOperators.From(new[] { 2, 4, 6 });
    var values = await StreamOperators.Merge(s1, s2).ToListAsync();
    // Order may vary, check all present
    Assert.Equal(6, values.Count);
    Assert.Contains(1, values);
    Assert.Contains(6, values);
  }
  
  [Fact]
  public async Task Merge_FromList()
  {
    var sources = new[] {
      StreamOperators.From(new[] { 1, 2 }),
      StreamOperators.From(new[] { 3, 4 })
    };
    var values = await StreamOperators.Merge(sources).ToListAsync();
    Assert.Equal(4, values.Count);
  }
}
// unnamed ends here
