// This file is auto-generated by organjsm tangle. Do not edit directly.
// Source: index.org

// [[file:index.org::14652]]
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Xunit;

namespace AgentRex.Tests;

public class MergeAllTests
{
  [Fact]
  public async Task MergeAll_FlattensStreamOfStreams()
  {
    async IAsyncEnumerable<IAsyncEnumerable<int>> StreamOfStreams()
    {
      yield return StreamOperators.From(new[] { 1, 2 });
      yield return StreamOperators.From(new[] { 3, 4 });
    }
    
    var values = await StreamOfStreams().MergeAll().ToListAsync();
    // Order may vary, check all present
    var sorted = values.OrderBy(x => x).ToList();
    Assert.Equal(new[] { 1, 2, 3, 4 }, sorted);
  }
  
  [Fact]
  public async Task MergeAll_HandlesEmptyOuterStream()
  {
    async IAsyncEnumerable<IAsyncEnumerable<int>> Empty()
    {
      yield break;
    }
    
    var values = await Empty().MergeAll().ToListAsync();
    Assert.Empty(values);
  }
}
// unnamed ends here
