// This file is auto-generated by organjsm tangle. Do not edit directly.
// Source: index.org

// [[file:index.org::2275]]
using System;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Xunit;

namespace AgentRex.Tests;

public class NeverTests
{
  [Fact]
  public async Task Never_DoesNotComplete()
  {
    using var cts = new CancellationTokenSource(10); // 10ms timeout
    await Assert.ThrowsAnyAsync<OperationCanceledException>(async () =>
    {
        await StreamOperators.Never<int>(cts.Token).ToListAsync();
    });
  }
}
// unnamed ends here
