// This file is auto-generated by organjsm tangle. Do not edit directly.
// Source: index.org

// [[file:index.org::1802]]
using System.Linq;
using System.Threading.Tasks;
using Xunit;

namespace AgentRex.Tests;

public class PeriodicTests
{
  [Fact]
  public async Task Periodic_EmitsAtIntervals()
  {
    var values = await StreamOperators.Periodic(10).Take(3).ToListAsync();
    Assert.Equal(3, values.Count);
  }
}
// unnamed ends here
