// This file is auto-generated by organjsm tangle. Do not edit directly.
// Source: index.org

// [[file:index.org::12525]]
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Xunit;

namespace AgentRex.Tests;

public class RecoverWithTests
{
  [Fact]
  public async Task RecoverWith_RecoversFromError()
  {
    async IAsyncEnumerable<int> Failing()
    {
      yield return 1;
      throw new InvalidOperationException("oops");
    }
    
    var values = await Failing()
      .RecoverWith(e => StreamOperators.From(new[] { 99 }))
      .ToListAsync();
    
    Assert.Equal(new[] { 1, 99 }, values);
  }
  
  [Fact]
  public async Task RecoverWith_PassesThroughSuccess()
  {
    var values = await StreamOperators.From(new[] { 1, 2, 3 })
      .RecoverWith(e => StreamOperators.From(new[] { 99 }))
      .ToListAsync();
    
    Assert.Equal(new[] { 1, 2, 3 }, values);
  }
}
// unnamed ends here
