// This file is auto-generated by organjsm tangle. Do not edit directly.
// Source: index.org

// [[file:index.org::20552]]
using System;
using System.Linq;
using System.Threading.Tasks;
using Xunit;

namespace AgentRex.Tests;

public class ReplayFactoryTests
{
  [Fact]
  public async Task ReplayFactory_CreatesStreamCopies()
  {
    var source = StreamOperators.From(new[] { 1, 2, 3 });
    var factory = source.ReplayFactory(2);
    await Task.Delay(100); // Let source complete
    
    var copy1 = await factory().ToListAsync();
    var copy2 = await factory().ToListAsync();
    
    Assert.NotEmpty(copy1);
    Assert.NotEmpty(copy2);
  }
}
// unnamed ends here
