// This file is auto-generated by organjsm tangle. Do not edit directly.
// Source: index.org

// [[file:index.org::20236]]
using System;
using System.Linq;
using System.Threading.Tasks;
using Xunit;

namespace AgentRex.Tests;

public class ReplayTests
{
  [Fact]
  public async Task Replay_MulticastsWithBuffer()
  {
    var source = StreamOperators.From(new[] { 1, 2, 3 });
    var replayed = source.Replay(2);
    await Task.Delay(100); // Let source complete
    
    var values = await replayed.Subscribe().ToListAsync();
    Assert.NotEmpty(values);
  }
  
  [Fact]
  public async Task Share_MulticastsWithoutBuffer()
  {
    // Share has no buffer, so we must subscribe immediately (not after source completes)
    var source = StreamOperators.From(new[] { 1, 2, 3 });
    var shared = source.Share();
    
    // Subscribe immediately - don't wait for source to complete
    var subscription = shared.Subscribe();
    var values = await subscription.ToListAsync();
    
    // With immediate subscription, we should get all values
    Assert.NotEmpty(values);
  }
}
// unnamed ends here
