// This file is auto-generated by organjsm tangle. Do not edit directly.
// Source: index.org

// [[file:index.org::19845]]
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Xunit;

namespace AgentRex.Tests;

public class ReplaySubjectTests
{
  [Fact]
  public async Task ReplaySubject_ReplaysBufferedValues()
  {
    var subject = new ReplaySubject<int>(2);
    subject.Next(1);
    subject.Next(2);
    subject.Next(3);
    subject.Complete();
    
    var values = await subject.Subscribe().ToListAsync();
    // Should get last 2 values (2, 3)
    Assert.Contains(2, values);
    Assert.Contains(3, values);
  }
}
// unnamed ends here
