// This file is auto-generated by organjsm tangle. Do not edit directly.
// Source: index.org

// [[file:index.org::13642]]
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Xunit;

namespace AgentRex.Tests;

public class RetryTests
{
  [Fact]
  public async Task Retry_RetriesUntilSuccess()
  {
    var attempts = 0;
    
    var values = await StreamOperators.Retry(() =>
    {
      return StreamFactory();
      
      async IAsyncEnumerable<int> StreamFactory()
      {
        attempts++;
        if (attempts < 3)
        {
          throw new InvalidOperationException($"fail {attempts}");
        }
        yield return attempts;
      }
    }, new RetryOptions { MaxAttempts = 3 }).ToListAsync();
    
    Assert.Equal(3, attempts);
    Assert.Equal(new[] { 3 }, values);
  }
  
  [Fact]
  public async Task Retry_ThrowsAfterMaxAttempts()
  {
    var attempts = 0;
    
    await Assert.ThrowsAsync<InvalidOperationException>(async () =>
    {
      await StreamOperators.Retry(() =>
      {
        return StreamFactory();
        
        async IAsyncEnumerable<int> StreamFactory()
        {
          attempts++;
          throw new InvalidOperationException("always fails");
 #pragma warning disable CS0162
          yield break;
 #pragma warning restore CS0162
        }
      }, new RetryOptions { MaxAttempts = 2 }).ToListAsync();
    });
    
    Assert.Equal(2, attempts);
  }
}
// unnamed ends here
