// This file is auto-generated by organjsm tangle. Do not edit directly.
// Source: index.org

// [[file:index.org::5302]]
using System;
using System.Linq;
using System.Threading.Tasks;
using Xunit;

namespace AgentRex.Tests;

public class ScanTests
{
  [Fact]
  public async Task Scan_AccumulatesWithSeed()
  {
    var values = await StreamOperators.From(new[] { 1, 2, 3 })
      .Scan(0, (acc, x) => acc + x)
      .ToListAsync();
    Assert.Equal(new[] { 0, 1, 3, 6 }, values);
  }
  
  [Fact]
  public async Task Scan_Product()
  {
    var values = await StreamOperators.From(new[] { 2, 3, 4 })
      .Scan(1, (acc, x) => acc * x)
      .ToListAsync();
    Assert.Equal(new[] { 1, 2, 6, 24 }, values);
  }
  
  [Fact]
  public async Task Scan_EmptyStream()
  {
    var values = await StreamOperators.From(Array.Empty<int>())
      .Scan(100, (acc, x) => acc + x)
      .ToListAsync();
    Assert.Equal(new[] { 100 }, values);
  }
}
// unnamed ends here
