// This file is auto-generated by organjsm tangle. Do not edit directly.
// Source: index.org

// [[file:index.org::17046]]
using System;
using System.Linq;
using System.Threading.Tasks;
using Xunit;

namespace AgentRex.Tests;

public class SinceStreamTests
{
  [Fact]
  public async Task SinceStream_WaitsForStart()
  {
    var source = StreamOperators.From(new[] { 1, 2, 3, 4 });
    var start = StreamOperators.Just(0);
    var values = await source.SinceStream(start).ToListAsync();
    Assert.NotEmpty(values);
    Assert.Equal(new[] { 1, 2, 3, 4 }, values);
  }
}
// unnamed ends here
