// This file is auto-generated by organjsm tangle. Do not edit directly.
// Source: index.org

// [[file:index.org::8786]]
using System.Linq;
using System.Threading.Tasks;
using Xunit;

namespace AgentRex.Tests;

public class SkipTests
{
  [Fact]
  public async Task Skip_FirstN()
  {
    var values = await StreamOperators.From(new[] { 1, 2, 3, 4, 5 })
      .Skip(2)
      .ToListAsync();
    Assert.Equal(new[] { 3, 4, 5 }, values);
  }
  
  [Fact]
  public async Task Skip_Zero()
  {
    var values = await StreamOperators.From(new[] { 1, 2, 3 })
      .Skip(0)
      .ToListAsync();
    Assert.Equal(new[] { 1, 2, 3 }, values);
  }
  
  [Fact]
  public async Task Skip_MoreThanAvailable()
  {
    var values = await StreamOperators.From(new[] { 1, 2 })
      .Skip(5)
      .ToListAsync();
    Assert.Empty(values);
  }
}
// unnamed ends here
