// This file is auto-generated by organjsm tangle. Do not edit directly.
// Source: index.org

// [[file:index.org::9956]]
using System;
using System.Linq;
using System.Threading.Tasks;
using Xunit;

namespace AgentRex.Tests;

public class SkipWhileTests
{
  [Fact]
  public async Task SkipWhile_SkipsWhileTrue()
  {
    var values = await StreamOperators.SkipWhile(
      x => x < 3,
      StreamOperators.From(new[] { 1, 2, 3, 4, 2, 1 })
    ).ToListAsync();
    Assert.Equal(new[] { 3, 4, 2, 1 }, values);
  }
  
  [Fact]
  public async Task SkipWhile_AllFail()
  {
    var values = await StreamOperators.SkipWhile(
      _ => false,
      StreamOperators.From(new[] { 1, 2, 3 })
    ).ToListAsync();
    Assert.Equal(new[] { 1, 2, 3 }, values);
  }
  
  [Fact]
  public async Task SkipWhile_AllPass()
  {
    var values = await StreamOperators.SkipWhile(
      _ => true,
      StreamOperators.From(new[] { 1, 2, 3 })
    ).ToListAsync();
    Assert.Empty(values);
  }
}
// unnamed ends here
