// This file is auto-generated by organjsm tangle. Do not edit directly.
// Source: index.org

// [[file:index.org::8031]]
using System;
using System.Linq;
using System.Threading.Tasks;
using Xunit;

namespace AgentRex.Tests;

public class SkipRepeatsTests
{
  [Fact]
  public async Task SkipRepeats_RemovesConsecutiveDuplicates()
  {
    var values = await StreamOperators.SkipRepeats(
      StreamOperators.From(new[] { 1, 1, 2, 2, 3, 1, 1 })
    ).ToListAsync();
    Assert.Equal(new[] { 1, 2, 3, 1 }, values);
  }
  
  [Fact]
  public async Task SkipRepeats_HandlesSingleValue()
  {
    var values = await StreamOperators.SkipRepeats(
      StreamOperators.From(new[] { 42 })
    ).ToListAsync();
    Assert.Equal(new[] { 42 }, values);
  }
  
  [Fact]
  public async Task SkipRepeatsWith_CustomEquality()
  {
    var values = await StreamOperators.SkipRepeatsWith(
      (a, b) => a.ToLower() == b.ToLower(),
      StreamOperators.From(new[] { "A", "a", "B", "b" })
    ).ToListAsync();
    Assert.Equal(new[] { "A", "B" }, values);
  }
}
// unnamed ends here
