// This file is auto-generated by organjsm tangle. Do not edit directly.
// Source: index.org

// [[file:index.org::9166]]
using System.Linq;
using System.Threading.Tasks;
using Xunit;

namespace AgentRex.Tests;

public class SliceTests
{
  [Fact]
  public async Task Slice_ExtractsRange()
  {
    var values = await StreamOperators.Slice(2, 5,
      StreamOperators.From(new[] { 0, 1, 2, 3, 4, 5 })
    ).ToListAsync();
    Assert.Equal(new[] { 2, 3, 4 }, values);
  }
  
  [Fact]
  public async Task Slice_EmptyRange()
  {
    var values = await StreamOperators.Slice(2, 2,
      StreamOperators.From(new[] { 0, 1, 2, 3, 4 })
    ).ToListAsync();
    Assert.Empty(values);
  }
  
  [Fact]
  public async Task Slice_BeyondLength()
  {
    var values = await StreamOperators.Slice(1, 10,
      StreamOperators.From(new[] { 0, 1, 2 })
    ).ToListAsync();
    Assert.Equal(new[] { 1, 2 }, values);
  }
}
// unnamed ends here
