// This file is auto-generated by organjsm tangle. Do not edit directly.
// Source: index.org

// [[file:index.org::3341]]
using System.Linq;
using System.Threading.Tasks;
using Xunit;

namespace AgentRex.Tests;

public class StartWithTests
{
  [Fact]
  public async Task StartWith_PrependsValue()
  {
    var values = await StreamOperators.StartWith(0, StreamOperators.From(new[] { 1, 2, 3 })).ToListAsync();
    Assert.Equal(new[] { 0, 1, 2, 3 }, values);
  }
  
  [Fact]
  public async Task StartWith_WorksWithEmptyStream()
  {
    var values = await StreamOperators.StartWith(42, StreamOperators.Empty<int>()).ToListAsync();
    Assert.Equal(new[] { 42 }, values);
  }
}
// unnamed ends here
