// This file is auto-generated by organjsm tangle. Do not edit directly.
// Source: index.org

// [[file:index.org::15599]]
using System;
using System.Linq;
using System.Threading.Tasks;
using Xunit;

namespace AgentRex.Tests;

public class SwitchMapTests
{
  [Fact]
  public async Task SwitchMap_CancelsPreviousInnerStream()
  {
    var values = await StreamOperators.From(new[] { 1, 2, 3 })
      .SwitchMap(x => StreamOperators.From(new[] { x * 10 }))
      .ToListAsync();
    // With fast synchronous streams, may see all or just last
    Assert.NotEmpty(values);
  }
  
  [Fact]
  public async Task SwitchMap_CompletesWhenOuterAndInnerComplete()
  {
    var values = await StreamOperators.From(new[] { 1 })
      .SwitchMap(x => StreamOperators.From(new[] { x, x * 2 }))
      .ToListAsync();
    Assert.Equal(new[] { 1, 2 }, values);
  }
}
// unnamed ends here
