// This file is auto-generated by organjsm tangle. Do not edit directly.
// Source: index.org

// [[file:index.org::10347]]
using System;
using System.Linq;
using System.Threading.Tasks;
using Xunit;

namespace AgentRex.Tests;

public class TakeUntilTests
{
  [Fact]
  public async Task TakeUntil_TakesUntilMatch()
  {
    var values = await StreamOperators.TakeUntil(
      x => x == 3,
      StreamOperators.From(new[] { 1, 2, 3, 4, 5 })
    ).ToListAsync();
    Assert.Equal(new[] { 1, 2 }, values);
  }
  
  [Fact]
  public async Task TakeUntil_NeverMatches()
  {
    var values = await StreamOperators.TakeUntil(
      _ => false,
      StreamOperators.From(new[] { 1, 2, 3 })
    ).ToListAsync();
    Assert.Equal(new[] { 1, 2, 3 }, values);
  }
  
  [Fact]
  public async Task TakeUntil_FirstMatches()
  {
    var values = await StreamOperators.TakeUntil(
      x => x == 1,
      StreamOperators.From(new[] { 1, 2, 3 })
    ).ToListAsync();
    Assert.Empty(values);
  }
}
// unnamed ends here
