// This file is auto-generated by organjsm tangle. Do not edit directly.
// Source: index.org

// [[file:index.org::8451]]
using System.Linq;
using System.Threading.Tasks;
using Xunit;

namespace AgentRex.Tests;

public class TakeTests
{
  [Fact]
  public async Task Take_FirstN()
  {
    var values = await StreamOperators.From(new[] { 1, 2, 3, 4, 5 })
      .Take(2)
      .ToListAsync();
    Assert.Equal(new[] { 1, 2 }, values);
  }
  
  [Fact]
  public async Task Take_MoreThanAvailable()
  {
    var values = await StreamOperators.From(new[] { 1, 2 })
      .Take(10)
      .ToListAsync();
    Assert.Equal(new[] { 1, 2 }, values);
  }
  
  [Fact]
  public async Task Take_Zero()
  {
    var values = await StreamOperators.From(new[] { 1, 2, 3 })
      .Take(0)
      .ToListAsync();
    Assert.Empty(values);
  }
}
// unnamed ends here
