// This file is auto-generated by organjsm tangle. Do not edit directly.
// Source: index.org

// [[file:index.org::9559]]
using System;
using System.Linq;
using System.Threading.Tasks;
using Xunit;

namespace AgentRex.Tests;

public class TakeWhileTests
{
  [Fact]
  public async Task TakeWhile_TakesWhileTrue()
  {
    var values = await StreamOperators.TakeWhile(
      x => x < 4,
      StreamOperators.From(new[] { 1, 2, 3, 4, 2, 1 })
    ).ToListAsync();
    Assert.Equal(new[] { 1, 2, 3 }, values);
  }
  
  [Fact]
  public async Task TakeWhile_AllPass()
  {
    var values = await StreamOperators.TakeWhile(
      _ => true,
      StreamOperators.From(new[] { 1, 2, 3 })
    ).ToListAsync();
    Assert.Equal(new[] { 1, 2, 3 }, values);
  }
  
  [Fact]
  public async Task TakeWhile_NonePass()
  {
    var values = await StreamOperators.TakeWhile(
      _ => false,
      StreamOperators.From(new[] { 1, 2, 3 })
    ).ToListAsync();
    Assert.Empty(values);
  }
}
// unnamed ends here
