// This file is auto-generated by organjsm tangle. Do not edit directly.
// Source: index.org

// [[file:index.org::5699]]
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Xunit;

namespace AgentRex.Tests;

public class TapTests
{
  [Fact]
  public async Task Tap_PerformsSideEffect()
  {
    var sideEffects = new List<int>();
    var values = await StreamOperators.Tap(
      x => sideEffects.Add(x),
      StreamOperators.From(new[] { 1, 2, 3 })
    ).ToListAsync();
    Assert.Equal(new[] { 1, 2, 3 }, values);
    Assert.Equal(new[] { 1, 2, 3 }, sideEffects);
  }
}
// unnamed ends here
