// This file is auto-generated by organjsm tangle. Do not edit directly.
// Source: index.org

// [[file:index.org::13023]]
using System;
using System.Linq;
using System.Threading.Tasks;
using Xunit;

namespace AgentRex.Tests;

public class ThrowErrorTests
{
  [Fact]
  public async Task ThrowError_CreatesFailingStream()
  {
    var error = new InvalidOperationException("test error");
    await Assert.ThrowsAsync<InvalidOperationException>(async () =>
    {
      await StreamOperators.ThrowError<int>(error).ToListAsync();
    });
  }
}
// unnamed ends here
