// This file is auto-generated by organjsm tangle. Do not edit directly.
// Source: index.org

// [[file:index.org::11949]]
using System;
using System.Linq;
using System.Threading.Tasks;
using Xunit;

namespace AgentRex.Tests;

public class ThrottleTests
{
  [Fact]
  public async Task Throttle_LeadingEmitsFirstValue()
  {
    var values = await StreamOperators.From(new[] { 1, 2, 3, 4, 5 })
      .Throttle(100, ThrottleOptions.LeadingOnly())
      .ToListAsync();
    // First value should be emitted immediately
    Assert.NotEmpty(values);
    Assert.Equal(1, values[0]);
  }
  
  [Fact]
  public async Task Throttle_TrailingEmitsLastValue()
  {
    var values = await StreamOperators.From(new[] { 1, 2, 3 })
      .Throttle(100, ThrottleOptions.TrailingOnly())
      .ToListAsync();
    // Last value should be emitted as trailing
    Assert.NotEmpty(values);
  }
  
  [Fact]
  public async Task Throttle_EmptyStream()
  {
    var values = await StreamOperators.From(Array.Empty<int>())
      .Throttle(100)
      .ToListAsync();
    Assert.Empty(values);
  }
}
// unnamed ends here
