// This file is auto-generated by organjsm tangle. Do not edit directly.
// Source: index.org

// [[file:index.org::2991]]
using System.Linq;
using System.Threading.Tasks;
using Xunit;

namespace AgentRex.Tests;

public class UnfoldTests
{
  [Fact]
  public async Task Unfold_GeneratesValuesUntilDone()
  {
    var values = await StreamOperators.Unfold(1, n => new UnfoldResult<int, int>(
      Value: n,
      NextSeed: n + 1,
      Done: n > 3
    )).ToListAsync();
    Assert.Equal(new[] { 1, 2, 3 }, values);
  }
  
  [Fact]
  public async Task Unfold_StopsImmediatelyWhenDone()
  {
    var values = await StreamOperators.Unfold(0, _ => new UnfoldResult<int, int>(
      Value: 999,
      NextSeed: 0,
      Done: true
    )).ToListAsync();
    Assert.Empty(values);
  }
}
// unnamed ends here
