// This file is auto-generated by organjsm tangle. Do not edit directly.
// Source: index.org

// [[file:index.org::16727]]
using System;
using System.Linq;
using System.Threading.Tasks;
using Xunit;

namespace AgentRex.Tests;

public class UntilStreamTests
{
  [Fact]
  public async Task UntilStream_StopsWhenStopEmits()
  {
    var source = StreamOperators.From(new[] { 1, 2, 3, 4, 5 });
    var stop = StreamOperators.Just(0);
    var values = await source.UntilStream(stop).ToListAsync();
    Assert.True(values.Count <= 5);
  }
}
// unnamed ends here
