// This file is auto-generated by organjsm tangle. Do not edit directly.
// Source: index.org

// [[file:index.org::18250]]
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Xunit;

namespace AgentRex.Tests;

public class WindowTests
{
  [Fact]
  public async Task Window_SplitsIntoFixedSizeGroups()
  {
    var source = StreamOperators.From(new[] { 1, 2, 3, 4, 5 });
    var values = await source.Window(2).ToListAsync();
    Assert.Equal(3, values.Count);
  }
}
// unnamed ends here
